using System.ComponentModel.DataAnnotations;

public enum Bank{
	[Display(Name="Banco ABC Brasil")]ABC = 246,
	[Display(Name="Banco Alfa")]ALFA = 025,
	[Display(Name="Banco Andbank")]ANDBANK = 065,
	[Display(Name="Banco Barclays")]BARCLAYS = 740,
	[Display(Name="Banco BBM")]BBM = 107,
	[Display(Name="Banco BMG")]BMG = 318,
	[Display(Name="Banco BNP Paribas Brasil")]BNP = 752,
	[Display(Name="Banco Bonsucesso")]BONSUCESSO = 218,
	[Display(Name="Bradesco")]BRADESCO = 237,
	[Display(Name="Banco Cetelem")]CETELEM = 739,
	[Display(Name="Citibank")]CITIBANK = 745,
	[Display(Name="Banco da Amazônia")]AMAZONIA = 003,
	[Display(Name="Banco Daycoval")]DAYCOVAL = 707,
	[Display(Name="Banco do Brasil")]BB = 001,
	[Display(Name="Banese")]BANESE = 047,
	[Display(Name="Banpara")]BANPARA = 037,
	[Display(Name="Banrisul")]BANRISUL = 041,
	[Display(Name="Banco do Nordeste")]BNB = 004,
	[Display(Name="Banco Fibra")]FIBRA = 224,
	[Display(Name="Banco Ficsa")]FICSA = 626,
	[Display(Name="Banco Guanabara")]GUANABARA = 612,
	[Display(Name="Banco Luso Brasileiro")]LUSO = 600,
	[Display(Name="Banco Mercantil do Brasil")]MERCANTIL = 389,
	[Display(Name="Banco Mizuho do Brasil")]MIZUHO = 370,
	[Display(Name="Banco Modal")]MODAL = 746,
	[Display(Name="Banco Original")]ORIGINAL = 212,
	[Display(Name="Banco PAN")]PAN = 623,
	[Display(Name="Banco Paulista")]PAULISTA = 611,
	[Display(Name="Banco Rendimento")]RENDIMENTO = 633,
	[Display(Name="Banco Safra")]SAFRA = 422,
	[Display(Name="Santander")]SANTANDER = 033,
	[Display(Name="Banco Topázio")]TOPAZIO = 082,
	[Display(Name="Banestes")]BANESTES = 021,
	[Display(Name="Banif-Banco Internacional do Funchal")]BANIF = 719,
	[Display(Name="BPN Brasil Banco Múltiplo")]MULTIPLO = 069,
	[Display(Name="BRB - Banco de Brasília")]BRB = 070,
	[Display(Name="Caixa Econômica Federal")]CAIXA = 104,
	[Display(Name="HSBC Bank Brasil")]HSBC = 399,
	[Display(Name="Itaú")]ITAU = 341,
	[Display(Name="Outro")]OUTRO = 99999
	
	
}